site_name: Arunkumar Velusamy
site_url: https://arunkumar-velusamy.com/

markdown_extensions:
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/profile.css

extra_javascript:
  - javascripts/menu.js
  - javascripts/email.js
